# Generated by Django 4.2 on 2023-04-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_image',
            field=models.ImageField(upload_to='doctor'),
        ),
    ]
